version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/log:/var/log/nginx
    ports:
      - 443:443
      - 80:80
    networks:
      subnet1:
        ipv4_address: 172.24.0.2
    restart: always

  elasticsearch:
    image: elasticsearch:8.6.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=stratocaster
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - xpack.license.self_generated.type=trial
    networks:
      subnet1:
        ipv4_address: 172.24.0.3
    restart: always

  logstash:
    image: logstash:8.6.0
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
      - 9600:9600
      - 5044:5044
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - monitoring.enabled=true
    networks:
      subnet1:
        ipv4_address: 172.24.0.4

  kibana:
    image: kibana:8.6.0
    container_name: kibana
    ports:
     - "5601:5601"
    networks:
      subnet1:
        ipv4_address: 172.24.0.5
    depends_on:
     - elasticsearch
  
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.6.0
    container_name: filebeat
    volumes:
      - ./nginx/log:/var/log/nginx
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      subnet1:
        ipv4_address: 172.24.0.6
    
networks:
  subnet1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/24